<?php namespace ProcessWire;

class AdminActionsUnorderedListToPages extends WireData implements Module {

    public static function getModuleInfo() {
        return array(
            'title' => 'Unordered List to Pages',
            'summary' => 'Creates a structure of new pages from an unordered list. Addon action for Admin Actions module.',
            'version' => '0.1.8',
            'author' => 'Robin Sallis',
            'href' => 'https://github.com/Toutouwai/AdminActionsUnorderedListToPages',
            'icon' => 'list-ul',
            'requires' => 'ProcessWire>=3.0.0, ProcessAdminActions>=0.9.0'
        );
    }

}
